---
app_root: /srv/lumiris
app_compose_dir: /srv/lumiris/Lumiris-Infra/prod
app_compose_file: docker-compose.prod.yml
app_services:
  - lumiris-api
  - lumiris-site
  - lumiris-app
  - lumiris-admin
app_force_recreate: false
